import { createHash, randomBytes } from 'node:crypto'
import { createReadStream, createWriteStream } from 'node:fs'
import { mkdir, rename, stat, unlink, rm } from 'node:fs/promises'
import { dirname, join, resolve, sep } from 'node:path'
import type { Readable } from 'node:stream'

/**
 * Where the bytes live.
 *
 * One implementation, local disk, and an interface narrow enough that another
 * can be added without touching anything above it. S3 is not implemented —
 * said plainly here rather than stubbed, so a deployment that needs it knows
 * before it discovers files going nowhere.
 */

export type BackendName = 'local' | 's3'

export interface StoredObject {
  key: string
  byteSize: number
  checksumSha256: string
}

export interface StorageBackend {
  readonly name: BackendName
  /** Why this backend cannot run here, or null. */
  unavailableReason(): string | null
  put(key: string, source: string): Promise<StoredObject>
  stream(key: string): Promise<Readable>
  remove(key: string): Promise<void>
  exists(key: string): Promise<boolean>
}

/**
 * A storage key.
 *
 * Built entirely from server-side values: the tenant, the category, a random
 * component and the type's own extension. Nothing a client sent appears in
 * it, so there is no filename to sanitise and no traversal to defend against
 * at this level — the defence is that the untrusted string is never used.
 *
 * Sharded two levels deep by the random prefix, because a directory holding
 * a hundred thousand files is slow to read on most filesystems.
 */
export function buildKey(tenantId: string, category: string, extension: string): string {
  const token = randomBytes(16).toString('hex')
  const safeCategory = /^[a-z_]+$/.test(category) ? category : 'other'
  const safeExt = /^[a-z0-9]{1,8}$/.test(extension) ? extension : 'bin'
  return [
    tenantId,
    safeCategory,
    token.slice(0, 2),
    token.slice(2, 4),
    `${token}.${safeExt}`,
  ].join('/')
}

/**
 * The root every local object lives under.
 *
 * Configurable, because a deployment will want it on a mounted volume rather
 * than beside the source.
 */
function localRoot(): string {
  return resolve(process.env.FILE_STORAGE_ROOT ?? join(process.cwd(), '.file-storage'))
}

/**
 * Resolves a key to a path inside the root, or refuses.
 *
 * Keys are generated by this module and should never contain a traversal, but
 * they reach here from the database, and a row could in principle have been
 * written by something else. Checking that the resolved path is still inside
 * the root costs nothing and removes the whole question.
 */
function resolveLocal(key: string): string {
  const root = localRoot()
  const full = resolve(root, key)
  if (full !== root && !full.startsWith(root + sep)) {
    throw new Error('Refusing a storage key that resolves outside the storage root')
  }
  return full
}

export const localBackend: StorageBackend = {
  name: 'local',

  unavailableReason(): string | null {
    return null
  },

  /**
   * Moves a staged upload into place.
   *
   * The checksum is taken by reading the staged file rather than trusting
   * anything computed earlier, so what is recorded describes the bytes that
   * actually landed. A rename across devices is not atomic and throws EXDEV,
   * which is why the fallback copies.
   */
  async put(key: string, source: string): Promise<StoredObject> {
    const target = resolveLocal(key)
    await mkdir(dirname(target), { recursive: true })

    const hash = createHash('sha256')
    let size = 0
    await new Promise<void>((done, fail) => {
      const read = createReadStream(source)
      read.on('data', (chunk) => {
        hash.update(chunk)
        size += chunk.length
      })
      read.on('error', fail)
      read.on('end', () => done())
    })

    try {
      await rename(source, target)
    } catch (e: any) {
      if (e?.code !== 'EXDEV') throw e
      // Staging directory on a different filesystem from the store.
      await new Promise<void>((done, fail) => {
        const read = createReadStream(source)
        const write = createWriteStream(target)
        read.on('error', fail)
        write.on('error', fail)
        write.on('close', () => done())
        read.pipe(write)
      })
      await unlink(source).catch(() => undefined)
    }

    return { key, byteSize: size, checksumSha256: hash.digest('hex') }
  },

  async stream(key: string): Promise<Readable> {
    const path = resolveLocal(key)
    await stat(path)
    return createReadStream(path)
  },

  async remove(key: string): Promise<void> {
    await rm(resolveLocal(key), { force: true })
  },

  async exists(key: string): Promise<boolean> {
    try {
      await stat(resolveLocal(key))
      return true
    } catch {
      return false
    }
  },
}

/**
 * S3 is not implemented.
 *
 * Every method refuses rather than silently doing nothing, and
 * unavailableReason says so before a single upload is attempted — a store
 * that accepts files and drops them is the worst possible failure for this
 * module, so it does not pretend.
 */
const NOT_IMPLEMENTED =
  'The S3 backend is not implemented. Set FILE_STORAGE_BACKEND=local, or add an '
  + 'S3 implementation in src/storage/backend.ts.'

export const s3Backend: StorageBackend = {
  name: 's3',
  unavailableReason: () => NOT_IMPLEMENTED,
  async put() { throw new Error(NOT_IMPLEMENTED) },
  async stream() { throw new Error(NOT_IMPLEMENTED) },
  async remove() { throw new Error(NOT_IMPLEMENTED) },
  async exists() { throw new Error(NOT_IMPLEMENTED) },
}

export function backendFor(name: BackendName): StorageBackend {
  return name === 's3' ? s3Backend : localBackend
}

/** The backend this deployment writes new files to. */
export function activeBackend(): StorageBackend {
  return backendFor(process.env.FILE_STORAGE_BACKEND === 's3' ? 's3' : 'local')
}

export { localRoot }
