-- 051: document storage.
--
-- Fourteen columns across this schema hold a file URL — students.profile_photo_url,
-- application_documents.file_url, leave_requests.document_url,
-- attendance_corrections.supporting_evidence_url and the rest — and there has
-- never been anything behind any of them. They are free-text fields that
-- accept whatever a caller types. Admissions tracks which documents it is
-- waiting for and has nowhere to put them; a fee receipt cannot be produced;
-- a student's photograph has a column and no uploader.
--
-- What is added here is one place files live, with the tenant boundary that
-- everything else in this system has.
--
-- The security decisions, since a file store is where they matter most:
--
--   The storage key is generated by the server. A client's filename never
--   reaches the filesystem, so there is no path to traverse. The original
--   name is kept for the download header and nothing else.
--
--   content_type is what the bytes were sniffed to be, not what the upload
--   claimed. declared_content_type keeps the claim, because a mismatch
--   between the two is worth being able to look up later.
--
--   Types are an allowlist. SVG and HTML are deliberately excluded: both are
--   executable in a browser, and serving one from the application's own
--   origin is stored cross-site scripting with extra steps.
--
--   Deletion is soft. A file referenced by an admission decision or an
--   attendance correction cannot simply stop existing, and a hard delete
--   would leave the reference pointing at nothing.

-- ---------------------------------------------------------------------------
-- The files
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS stored_files (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id             UUID NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,

  -- Where the bytes are. Server-generated; never derived from anything a
  -- client sent.
  backend               VARCHAR(20) NOT NULL DEFAULT 'local',
  storage_key           TEXT NOT NULL,

  -- What the uploader called it. Used for the download filename and shown in
  -- listings. Never used to build a path.
  original_name         VARCHAR(255) NOT NULL,

  -- What the bytes actually are, established by reading them.
  content_type          VARCHAR(100) NOT NULL,
  -- What the upload said they were. Kept because a mismatch is a signal.
  declared_content_type VARCHAR(100),

  byte_size             BIGINT NOT NULL,
  checksum_sha256       CHAR(64) NOT NULL,

  category              VARCHAR(40) NOT NULL DEFAULT 'other',

  -- What this file is attached to. Deliberately not a foreign key: files hang
  -- off applications, students, employees, leave requests and corrections,
  -- and a column per owner would mean a migration every time a new kind of
  -- thing needs an attachment.
  owner_type            VARCHAR(50),
  owner_id              UUID,

  uploaded_by           UUID REFERENCES users(id) ON DELETE SET NULL,

  -- No scanner is wired in. 'skipped' is the honest default and says so,
  -- rather than 'clean', which would claim an inspection that never happened.
  scan_status           VARCHAR(20) NOT NULL DEFAULT 'skipped',
  scan_detail           TEXT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Soft delete: the row survives so a reference to it still resolves, and
  -- the bytes are removed separately by whatever sweeps expired files.
  deleted_at            TIMESTAMPTZ,
  deleted_by            UUID REFERENCES users(id) ON DELETE SET NULL,
  delete_reason         TEXT,

  CONSTRAINT stored_files_backend CHECK (backend IN ('local', 's3')),
  CONSTRAINT stored_files_size CHECK (byte_size > 0),
  CONSTRAINT stored_files_checksum CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT stored_files_scan CHECK (scan_status IN ('skipped', 'pending', 'clean', 'infected')),
  CONSTRAINT stored_files_category CHECK (category IN (
    'profile_photo', 'application_document', 'leave_document',
    'attendance_evidence', 'fee_receipt', 'incident_attachment',
    'report', 'other'
  )),
  -- An allowlist, checked here as well as in the service. SVG and HTML are
  -- absent on purpose.
  CONSTRAINT stored_files_content_type CHECK (content_type IN (
    'application/pdf',
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'text/plain', 'text/csv',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/msword', 'application/vnd.ms-excel'
  )),
  CONSTRAINT stored_files_deleted_has_reason
    CHECK (deleted_at IS NULL OR delete_reason IS NOT NULL),
  CONSTRAINT stored_files_name CHECK (LENGTH(TRIM(original_name)) > 0)
);

-- One row per object. Two rows pointing at the same key would mean deleting
-- one destroys the other's bytes.
CREATE UNIQUE INDEX IF NOT EXISTS uq_stored_files_key
  ON stored_files (backend, storage_key);

CREATE INDEX IF NOT EXISTS idx_stored_files_tenant
  ON stored_files (tenant_id, category, created_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_stored_files_owner
  ON stored_files (tenant_id, owner_type, owner_id)
  WHERE deleted_at IS NULL;

-- Finding an identical upload within a tenant, so the same transcript sent
-- twice does not occupy twice the space.
CREATE INDEX IF NOT EXISTS idx_stored_files_checksum
  ON stored_files (tenant_id, checksum_sha256)
  WHERE deleted_at IS NULL;

-- What a file is and where it lives are fixed once written. Changing either
-- would mean the row describes bytes other than the ones it was created for.
CREATE OR REPLACE FUNCTION guard_stored_file() RETURNS TRIGGER AS $storedfile$
BEGIN
  IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id THEN
    RAISE EXCEPTION 'A file cannot be moved between tenants'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.storage_key IS DISTINCT FROM OLD.storage_key
     OR NEW.backend IS DISTINCT FROM OLD.backend
     OR NEW.checksum_sha256 IS DISTINCT FROM OLD.checksum_sha256
     OR NEW.byte_size IS DISTINCT FROM OLD.byte_size
     OR NEW.content_type IS DISTINCT FROM OLD.content_type THEN
    RAISE EXCEPTION 'What a stored file is and where it lives are fixed once it is written'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
    RAISE EXCEPTION 'A deleted file is not undeleted; upload it again'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$storedfile$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_stored_files_guard ON stored_files;
CREATE TRIGGER trg_stored_files_guard
  BEFORE UPDATE ON stored_files
  FOR EACH ROW EXECUTE FUNCTION guard_stored_file();

-- ---------------------------------------------------------------------------
-- Quota
-- ---------------------------------------------------------------------------

-- Without a ceiling, one tenant filling a shared disk takes every other
-- tenant down with it. Maintained by trigger so the check is a single row
-- read rather than a sum over every file the tenant owns.
CREATE TABLE IF NOT EXISTS tenant_storage_quota (
  tenant_id   UUID PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  quota_bytes BIGINT NOT NULL DEFAULT 5368709120,   -- 5 GiB
  used_bytes  BIGINT NOT NULL DEFAULT 0,
  file_count  INTEGER NOT NULL DEFAULT 0,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenant_storage_quota_positive CHECK (quota_bytes > 0 AND used_bytes >= 0)
);

CREATE OR REPLACE FUNCTION maintain_storage_quota() RETURNS TRIGGER AS $quota$
DECLARE
  delta_bytes BIGINT := 0;
  delta_count INTEGER := 0;
  target UUID;
BEGIN
  IF TG_OP = 'INSERT' THEN
    target := NEW.tenant_id;
    delta_bytes := NEW.byte_size;
    delta_count := 1;
  ELSIF TG_OP = 'DELETE' THEN
    target := OLD.tenant_id;
    IF OLD.deleted_at IS NULL THEN
      delta_bytes := -OLD.byte_size;
      delta_count := -1;
    END IF;
  ELSE
    target := NEW.tenant_id;
    -- A soft delete releases the allowance; nothing else changes it.
    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
      delta_bytes := -NEW.byte_size;
      delta_count := -1;
    END IF;
  END IF;

  IF delta_bytes <> 0 OR delta_count <> 0 THEN
    INSERT INTO tenant_storage_quota (tenant_id, used_bytes, file_count)
    VALUES (target, GREATEST(delta_bytes, 0), GREATEST(delta_count, 0))
    ON CONFLICT (tenant_id) DO UPDATE
      SET used_bytes = GREATEST(tenant_storage_quota.used_bytes + delta_bytes, 0),
          file_count = GREATEST(tenant_storage_quota.file_count + delta_count, 0),
          updated_at = CURRENT_TIMESTAMP;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$quota$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_stored_files_quota ON stored_files;
CREATE TRIGGER trg_stored_files_quota
  AFTER INSERT OR UPDATE OR DELETE ON stored_files
  FOR EACH ROW EXECUTE FUNCTION maintain_storage_quota();

-- ---------------------------------------------------------------------------
-- Access log
-- ---------------------------------------------------------------------------

-- Who read which document, and when. An admissions certificate or a medical
-- note is exactly the sort of thing somebody later asks who looked at.
CREATE TABLE IF NOT EXISTS file_access_log (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  file_id     UUID NOT NULL REFERENCES stored_files(id) ON DELETE CASCADE,
  actor_id    UUID REFERENCES users(id) ON DELETE SET NULL,
  action      VARCHAR(20) NOT NULL,
  ip_address  VARCHAR(45),
  user_agent  TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT file_access_log_action CHECK (action IN ('download', 'view', 'denied'))
);

CREATE INDEX IF NOT EXISTS idx_file_access_log_file
  ON file_access_log (file_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_file_access_log_tenant
  ON file_access_log (tenant_id, occurred_at DESC);

CREATE OR REPLACE FUNCTION prevent_file_access_log_change() RETURNS TRIGGER AS $falog$
BEGIN
  RAISE EXCEPTION 'File access records are immutable. % is not permitted.', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$falog$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_file_access_log_no_update ON file_access_log;
DROP TRIGGER IF EXISTS trg_file_access_log_no_delete ON file_access_log;

CREATE TRIGGER trg_file_access_log_no_update
  BEFORE UPDATE ON file_access_log
  FOR EACH ROW EXECUTE FUNCTION prevent_file_access_log_change();

-- Removing the file or the tenant cascades; a direct delete is refused.
CREATE TRIGGER trg_file_access_log_no_delete
  BEFORE DELETE ON file_access_log
  FOR EACH ROW
  WHEN (pg_trigger_depth() = 0)
  EXECUTE FUNCTION prevent_file_access_log_change();

-- ---------------------------------------------------------------------------
-- Wiring the existing columns to real files
-- ---------------------------------------------------------------------------

-- The URL columns stay, because callers and the UI read them, but each gains
-- a file id so a reference can point at something that exists. The URL
-- becomes the download path for that file rather than free text.
ALTER TABLE application_documents
  ADD COLUMN IF NOT EXISTS file_id UUID REFERENCES stored_files(id) ON DELETE SET NULL;

ALTER TABLE students
  ADD COLUMN IF NOT EXISTS profile_photo_file_id UUID REFERENCES stored_files(id) ON DELETE SET NULL;

ALTER TABLE leave_requests
  ADD COLUMN IF NOT EXISTS document_file_id UUID REFERENCES stored_files(id) ON DELETE SET NULL;

ALTER TABLE attendance_corrections
  ADD COLUMN IF NOT EXISTS evidence_file_id UUID REFERENCES stored_files(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_application_documents_file
  ON application_documents (file_id) WHERE file_id IS NOT NULL;
