#!/usr/bin/env node
/**
 * Generates the app's brand assets from the master artwork.
 *
 *   node scripts/brand-assets.mjs
 *
 * Source: logo/favicon.svg at the repository root — a vector trace of the
 * JJELOTECH SYSTEMS logo (sun, chevron, "JjeloTech" wordmark, tagline) on a
 * black square. Everything the app shows is derived from it, so changing the
 * artwork means replacing that file and running this again:
 *
 *   src/components/brandMarkPaths.ts   the mark (sun + chevron) for BrandLogo.tsx
 *   public/logos/favicon.svg           the mark on a dark rounded tile
 *   public/logos/jjelotech-logo.svg    the full lockup (with tagline) on a transparent ground
 *   public/logos/jjelotech-logo-wordmark.svg   mark and wordmark, without the tagline
 *
 * The mark is the orange and blue paths; the wordmark (near-white) and
 * tagline (grey) are the rest. The black background square is dropped, so
 * every asset works on light and dark surfaces alike.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const FRONT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = path.resolve(FRONT, '..', '..', 'logo', 'favicon.svg')

const MARK_COLOURS = new Set(['#FE9401', '#0068F5', '#0091F8'])
const LOCKUP_COLOURS = new Set([...MARK_COLOURS, '#FEFEFE', '#BCBABC'])

const svg = fs.readFileSync(SOURCE, 'utf8')
const paths = [...svg.matchAll(/<path([^>]*)\/>/g)].map((m) => ({
  fill: (m[1].match(/fill="([^"]+)"/) || [])[1] ?? null,
  d: (m[1].match(/ d="([^"]+)"/) || [])[1],
})).filter((p) => p.d)

/** Bounding box of absolute path coordinates (the trace uses only M/L/C/Z). */
function bbox(ds) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
  for (const d of ds) {
    if (/[a-y]/.test(d.replace(/e-?\d/g, ''))) throw new Error('relative path commands are not supported')
    const nums = d.match(/-?\d*\.?\d+(?:e-?\d+)?/g).map(Number)
    for (let i = 0; i + 1 < nums.length; i += 2) {
      minX = Math.min(minX, nums[i]); maxX = Math.max(maxX, nums[i])
      minY = Math.min(minY, nums[i + 1]); maxY = Math.max(maxY, nums[i + 1])
    }
  }
  return { minX, minY, maxX, maxY }
}

function viewBox(b, pad, square) {
  let w = b.maxX - b.minX, h = b.maxY - b.minY
  let x = b.minX, y = b.minY
  if (square) {
    const s = Math.max(w, h)
    x -= (s - w) / 2; y -= (s - h) / 2; w = h = s
  }
  const r = (n) => Math.round(n * 10) / 10
  return [r(x - pad), r(y - pad), r(w + 2 * pad), r(h + 2 * pad)]
}

const mark = paths.filter((p) => MARK_COLOURS.has(p.fill))
const lockup = paths.filter((p) => LOCKUP_COLOURS.has(p.fill))
if (mark.length === 0) throw new Error('no mark paths found in ' + SOURCE)

const markBox = viewBox(bbox(mark.map((p) => p.d)), 8, true)

// ---------------------------------------------------------------- TS module
const ts = `// GENERATED by scripts/brand-assets.mjs from logo/favicon.svg — do not edit.
// The JJELOTECH SYSTEMS mark: sun and chevron, on a transparent ground.

export const MARK_VIEWBOX = '${markBox.join(' ')}';

export const MARK_PATHS: ReadonlyArray<{ fill: string; d: string }> = ${JSON.stringify(
  mark.map(({ fill, d }) => ({ fill, d })), null, 2)};
`
fs.writeFileSync(path.join(FRONT, 'src', 'components', 'brandMarkPaths.ts'), ts)

// ---------------------------------------------------------------- favicon
// The mark on a dark rounded tile: the rays are thin, and at 16 px they need
// a ground of their own to survive a light or dark browser tab.
const [mx, my, ms] = markBox
const tilePad = ms * 0.12
const tile = [mx - tilePad, my - tilePad, ms + 2 * tilePad].map((n) => Math.round(n * 10) / 10)
const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${tile[0]} ${tile[1]} ${tile[2]} ${tile[2]}">
  <title>JJELOTECH SYSTEMS</title>
  <rect x="${tile[0]}" y="${tile[1]}" width="${tile[2]}" height="${tile[2]}" rx="${Math.round(tile[2] * 0.22)}" fill="#0b1020"/>
${mark.map((p) => `  <path fill="${p.fill}" d="${p.d}"/>`).join('\n')}
</svg>
`
fs.writeFileSync(path.join(FRONT, 'public', 'logos', 'favicon.svg'), favicon)

// ---------------------------------------------------------------- lockup
// The trace cuts letter counters (the hole in "o", "e", …) with separate
// black shapes drawn on top of the letters. Dropping them fills every hole;
// keeping them paints black holes on a transparent logo. So they become a
// mask: the letters show everywhere except inside the counters, and the
// holes are genuinely transparent on any background.
const holes = paths.filter((p, i) => !p.fill && i !== 0) // path 0 is the black background square
function lockupFile(name, withTagline) {
  const parts = lockup.filter((p) => withTagline || p.fill !== '#BCBABC')
  const box = viewBox(bbox(parts.map((p) => p.d)), 16, false)
  const out = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box.join(' ')}">
  <title>JJELOTECH SYSTEMS${withTagline ? ' — Engineering the Dawn of Enterprise Systems' : ''}</title>
  <defs>
    <mask id="counters" maskUnits="userSpaceOnUse" x="0" y="0" width="1254" height="1254">
      <rect width="1254" height="1254" fill="#fff"/>
${holes.map((p) => `      <path fill="#000" d="${p.d}"/>`).join('\n')}
    </mask>
  </defs>
  <g mask="url(#counters)">
${parts.map((p) => `    <path fill="${p.fill}" d="${p.d}"/>`).join('\n')}
  </g>
</svg>
`
  fs.writeFileSync(path.join(FRONT, 'public', 'logos', name), out)
  return box
}
const lockupBox = lockupFile('jjelotech-logo.svg', true)
lockupFile('jjelotech-logo-wordmark.svg', false)

console.log(`mark: ${mark.length} paths, viewBox ${markBox.join(' ')}`)
console.log(`lockup: ${lockup.length} paths, viewBox ${lockupBox.join(' ')}`)
console.log(`counters masked: ${holes.length}`)
console.log('wrote src/components/brandMarkPaths.ts and public/logos/{favicon,jjelotech-logo,jjelotech-logo-wordmark}.svg')
